language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ttuom1nen/docker-exercise-3 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ttuom1nen/docker-exercise-3 npm test -- --coverage

after_success:
  - docker build -t ttuom1nen/client ./client
  - docker build -t ttuom1nen/nginx ./nginx
  - docker build -t ttuom1nen/server ./server
  - docker build -t ttuom1nen/worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push ttuom1nen/client
  - docker push ttuom1nen/nginx
  - docker push ttuom1nen/server
  - docker push ttuom1nen/worker
